FROM centos:7

ARG MINIFI_BINARY
ARG MINIFI_VERSION
ARG UID=1000
ARG GID=50

RUN curl -o epel-release-7-9.noarch.rpm http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm && \
    rpm -ivh epel-release-7-9.noarch.rpm && \
    rm epel-release-7-9.noarch.rpm && \
    yum update -y && \
    yum install -y \
      libcurl \
      leveldb \
      libuuid \
      boost \
      openssl && \
    yum clean all

RUN groupadd -g $GID minifi || groupmod -n minifi `getent group $GID | cut -d: -f1` && \
    useradd --shell /bin/bash -u $UID -g $GID -m minifi && \
    mkdir -p /home/minifi && \
    chown -R minifi:minifi /home/minifi

ENV MINIFI_HOME /opt/minifi/nifi-minifi-cpp-$MINIFI_VERSION
ADD $MINIFI_BINARY /opt/minifi

RUN chown -R minifi:minifi /opt/minifi
USER minifi
WORKDIR $MINIFI_HOME
CMD $MINIFI_HOME/bin/minifi.sh run
